### ISSUE TITLE
How to get the Device in ESPHOME / Home Assistant

### ISSUE THREAD

**Issue by f45tb00t** [M4GNV5/esphome-SK20-Nebula-Light#12]
Hi,

everything is flashed on works pretty well. Actually I did some research how to get the device now in ESPHOME and Home Assistant. But unfortunately I did not find that much information about that.

Any help in the right direction would be really nice. 

Thanks in advance.

**Comment by helgek** [comment]
Congrats!
You'll get it into esphome by creating whatever device in esphome and overwriting the yaml content with the yaml configuration you used to flash your projector with. Then the device should show as "online" and future config changes you can flash from inside esphome in home assistant

**Comment by f45tb00t** [comment]
Where can I find the completel yaml which has been flashed? 

only yaml files I can find:
recommended_base.yaml
secrets.yaml

**Comment by helgek** [comment]
Did your device connect to your network, did you provide wifi credentials either through your home assistant yaml or manually through your own yaml configuration?

**Comment by f45tb00t** [comment]
The device is connected to the network. I added the wifi ssid, password, wifi_fallback_password, ota and api password in the secrets.yaml as described
I can reach the interface via http in my wifi

**Comment by helgek** [comment]
This is my code which you can adapt, just double check if the platform and board are correct for you too, but I guess they should be if you were able to use the same config from M4GNV5:

```
substitutions:
  device_name: "Star Projector"
  #store_scene_to_flash: "false"
  friendly_name: Star Projector Bedroom
# Modell SK20

# by default controlling is done via the button and via the web interface
# if you use homeassistant you can uncomment below code:
#api:
#  password: !secret api_password

packages:
  remote_package:
    url: https://github.com/M4GNV5/esphome-SK20-Nebula-Light.git
    ref: master
    #files: [recommended_base.yaml, platform_bk72xx.yaml, nebula_light_device.yaml]
    files: [nebula_light_device.yaml]

esphome:
  name: star-projector-bedroom-device
  friendly_name: ${friendly_name}
  #on_boot:
   # - lambda: |-
    #    id(my_ota).set_auth_password("");
bk72xx:
  board: wb3s

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  power_save_mode: none

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.87
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  ap:
    ssid: "Fallback AP"
    password: !secret wifi_fallback_password

captive_portal:

logger:
  level: INFO

ota:
  - platform: esphome
    password: !secret ota_password
  #password: !secret ota_password
  #id: my_ota

web_server:
  port: 80

api:

```
