### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by ignacio82** [M4GNV5/esphome-SK20-Nebula-Light#4]
I was able to flash the firmware but it is not connecting to my network nor I can connect to fallback. Is there a way of reflashing this to see if I can get it to work?

**Comment by helgek** [comment]
is the fallback ssid available in the network? and did you insert the correct credentials in the yaml config file? In case you used wrong credentials you could temporarily adjust the access point settings of your network.

**Comment by ignacio82** [comment]
this is what I did

```
wifi_ssid: mi-red-iot
wifi_password: mypassword
wifi_fallback_password: mypassword
ota_password: Bz4HX3@@nxKpyTg$A
api_password: ^G^^3jcjrimjo2SW2wDNpfr3KP9rx6B2
```

I can see a fallback wifi network, but I cannot connect to it. Should i have done "mypassword" instead???

**Comment by helgek** [comment]
you can't connect to it means
- your computer can't connect and gives you an error message?
- the password doesn't work?
- the connection is established but you can't connect to the webserver?
there are several scenarious, you need to be more specific.

**Comment by helgek** [comment]
also did you check if the device shows up in your router as device to ensure it really doesn't connect to your wifi network?

**Comment by helgek** [comment]
and one more thing: You should always separate your 2.4GHz network with a different SSID. 5GHz and 2.4GHz networks under one SSID can cause issues for 2.4GHz smart home devices to connect. So in case this could be an issue you could give your 5GHz a different SSID, at least temporarily, to see if this solves a connection issue of the device.

**Comment by ignacio82** [comment]
I can see Fallback AP but I cannot connect to it, it says the password is incorrect.

![image](https://github.com/M4GNV5/esphome-SK20-Nebula-Light/assets/1833309/6f0cd91a-69c5-4668-9b95-4416ba809634)

I have a separate 2.4 GHz network (mi-red-iot) that I use for these cases.

**Comment by helgek** [comment]
and you tried 
wifi_fallback_password: mypassword 
I assume

**Comment by ignacio82** [comment]
yes

**Comment by helgek** [comment]
I never tried the fallback AP. I can test it on my devices later and let you know

**Comment by ignacio82** [comment]
could the problem be that i didn't use quotation marks around the password??

**Comment by helgek** [comment]
Are you sure that you used the correct yaml notation for wifi? I can see that you're showing the notation from secrets.yaml.  When you compiled the nebula yaml did you have a secrets.yaml configured? For the compilation and flashing I put my wifi credentials directly into the nebula yaml file using this notation:

```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  
ap:
  ssid: "Fallback AP"
  password: !secret wifi_fallback_password
```
    

I do passwords without quotes too (both directly in the device yaml as well as in the secrets.yaml. That's certainly not the issue.

**Comment by ignacio82** [comment]
I did copy and paste from your instruction. This is what I have:

```
substitutions:
  device_name: "Star Projector"
  store_scene_to_flash: "false"

# by default controlling is done via the button and via the web interface
# if you use homeassistant you can uncomment below code:
#api:
#  password: !secret api_password

packages:
  remote_package:
    url: https://github.com/M4GNV5/esphome-SK20-Nebula-Light.git
    ref: master
    files: [recommended_base.yaml, platform_bk72xx.yaml, nebula_light_device.yaml]
```

**Comment by helgek** [comment]
I'm not the creator of this jailbreak, just a consumer. Just looked at the instructions, again, yes this look right in your config. I didn't follow these instructions regarding the wifi credentials, I didn't use the secrets.yaml. I added the reference to my secrets.yaml later in the ESPHome GUI in Home Assistant.

**Comment by helgek** [comment]
I don't know if esphome CLI may require quotes for the passwords in the secrets.yaml due to some potential bug, but I don't would expect this to be the case (but one never knows of course).

**Comment by Cossid** [comment]
Lack of quotes should not matter as long as your passwords don't contain a quote character within them.
It sounds like CloudCutter worked successfully, and installed the 3rd party firmware you supplied, as it has the AP fallback name you provided.  ESPHome won't compile if secrets are used as a substitution, and not present in the secrets file, so either it had a different value from not being saved at an expected point, or you're typing something wrong.

Not sure if you copied the example secrets.yaml file initially, in which case see if your fallback password is literally `<some random password>` if it didn't save from when you replaced with `mypassword` (which seems somewhat plausable since it also wouldn't connect to your network with specific credentials).

Failing that, you would need to attach your .ug.bin file to see what was actually compiled, but be warned, it will contain any password you compiled in.

**Comment by ignacio82** [comment]
[here](https://drive.google.com/file/d/1WPMBasuzynjzUfwdGV7a0A3b1REp8KRI/view?usp=sharing) is the `.ug.bin` Thanks for the help

**Comment by Cossid** [comment]
It looks like you had incomplete data in your secrets, but neither the defaults in the guide nor what you replaced them with.

Here is what I'm finding:
```yaml
wifi_ssid: some-ssid
wifi_password: some-pwd
wifi_fallback_password: some-fallback-pwd
ota_password: some-ota-pwd
```
and I can't immediately find an API password (it looks like you probably had that commented out).

**Comment by ignacio82** [comment]
Thanks. I was able to connect to the fallback and then to my wifi. Given that the API is commented out, how do can I fix that so j can actually use this with home assistant?

**Comment by Cossid** [comment]
You can just add it to your next OTA update like any other ESPHome changes.  You'll need to use that OTA password that is currently on the device, or change it using the following guide: https://esphome.io/components/ota.html#changing-an-existing-password

**Comment by helgek** [comment]
You can also add encryption later, I'd first make sure that the device works in Home Assistant. You need to add the yaml to esphome as well in home assistant if you want to update the device within Home Assistant.

**Comment by ignacio82** [comment]
Sorry, I'm very new to this so I'm not following. I can see my device connected to my router:

![image](https://github.com/M4GNV5/esphome-SK20-Nebula-Light/assets/1833309/f8c7b072-cd0d-4bc0-b6b9-2058777da50f)

However, I cannot see it on my ESPHome dashboard 

![image](https://github.com/M4GNV5/esphome-SK20-Nebula-Light/assets/1833309/1318c75b-95ab-419b-b473-f8a92f589902)

Nor in home assistant auto discovery. Thanks for the help.

**Comment by Cossid** [comment]
How did you compile your original firmware?  Add the same config as a new device in your dashboard (which you could have done originally instead of the CLI)

**Comment by ignacio82** [comment]
I followed (these](https://github.com/M4GNV5/esphome-SK20-Nebula-Light) instructions

**Comment by Cossid** [comment]
Copy the contents of your nebula.yaml and add a new device in ESPHome dashboard, select any board (it doesn't matter which, you're going to override the info), and then edit that device and paste everything from yor nebula.yaml, and verify your secrets are set up correctly.

You may have to follow the guide I posted above if your OTA passwords are different.

**Comment by helgek** [comment]
One easy way is:
1. create a generic ESP32 device in the dashboard. 
2. edit the device yaml and insert the yaml config for your device.

**Comment by ignacio82** [comment]
Thanks everyone! I got it to work and it is so much better than having to deal with tuya !

**Comment by helgek** [comment]
Congrats, great to know you figured it out!

**Comment by slishak** [comment]
I experienced exactly the same issue. I think the problem is that `recommended_base.yaml` is pulled from the remote package, but it refers to the local `secrets.yaml` which is not allowed (see https://esphome.io/guides/configuration-types.html#remote-git-packages). Instead, it seems to pick up the example [secrets.yaml](https://github.com/M4GNV5/esphome-SK20-Nebula-Light/blob/master/secrets.yaml).

I fixed it by just copying the contents of `recommended_base.yaml` into my local `nebula.yaml` and removing the reference to `recommended_base.yaml`.

**Comment by metaljay** [comment]
Sorry to bump and old thread - I also get this error just with the same starlight you have, running on a raspberry pi (followed the instructions from cloud cutter)doesn't matter what firmware I try, same error not connecting:
```
[?] Select the firmware version and name: 1.1.2 - BK7231T / oem_bk7231t_light3_laser_nanxin
 ► 1.1.2 - BK7231T / oem_bk7231t_light3_laser_nanxin



Performing safety checks to make sure all required ports are available
Checking UDP port 53... Available.
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
Safety checks complete.

[?] Select your custom firmware file for BK7231T chip: ESPHome-Kickstart-v23.08.29_bk7231t_app.ota.ug.bin
 ► ESPHome-Kickstart-v23.08.29_bk7231t_app.ota.ug.bin
   esphome_2024.10.3_generic-bk7231t-qfn32-tuya_bk7231t_lt1.7.0.uf2
   image_bk7231t_app.ota.ug.bin
   OpenBeken-v1.17.697_bk7231t.ug.bin

Selected Device Slug: tuya-generic-sk20-star-projector-v1.1.2
Selected Profile: oem-bk7231t-light3-laser-nanxin-1.1.2-sdk-1.0.2-40.00
Selected Firmware: ESPHome-Kickstart-v23.08.29_bk7231t_app.ota.ug.bin

================================================================================
Place your device in AP (slow blink) mode.  This can usually be accomplished by either:
Power cycling off/on - 3 times and wait for the device to fast-blink, then repeat 3 more times.  Some devices need 4 or 5 times on each side of the pause
Long press the power/reset button on the device until it starts fast-blinking, then releasing, and then holding the power/reset button again until the device starts slow-blinking.
See https://support.tuya.com/en/help/_detail/K9hut3w10nby8 for more information.
================================================================================

Wiping NetworkManager configs
Scanning for open Tuya SmartLife AP
......
Found access point name: "SmartLife-BB3D", trying to connect...
Error: Connection activation failed: 802.1X supplicant took too long to authenticate.
Wiping NetworkManager configs
..
Found access point name: "SmartLife-BB3D", trying to connect...
Error: Connection activation failed: 802.1X supplicant took too long to authenticate.
Wiping NetworkManager configs
..
Found access point name: "SmartLife-BB3D", trying to connect...
Error: Connection activation failed: 802.1X supplicant took too long to authenticate.
Wiping NetworkManager configs
..
Found access point name: "SmartLife-BB3D", trying to connect...
Error: Connection activation failed: 802.1X supplicant took too long to authenticate.
Wiping NetworkManager configs
..
Found access point name: "SmartLife-BB3D", trying to connect...
Error: Connection activation failed: 802.1X supplicant took too long to authenticate.
Error, could not connect to SSID.
Failed to connect, please run this script again
``` 

here is my yaml:
```
esphome:
  name: nebula
  friendly_name: Star Projector

bk72xx:
  board: generic-bk7231t-qfn32-tuya

# Enable logging
logger:
    level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "+cbxE5JnGw3B1Wx9/VSuBeVeXZIRCA0/Ag/x2y5JHMw="

ota:
  - platform: esphome
    password: "29b4a11d74c78526ea7353af8d0f5b83"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nebula Fallback Hotspot"
    password: "j7y5k9D5RUmq"

captive_portal:

web_server:
  port: 80

packages:
  remote_package:
    url: https://github.com/M4GNV5/esphome-SK20-Nebula-Light.git
    ref: master
    files: [platform_bk72xx.yaml, nebula_light_device.yaml]   
```
